import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextThemeProvider from "@/providers/next-theme";
import NextAuthProvider from "@/providers/next-auth-provider";
import MainContextProvider from "@/context";
import Header from "@/components/ui/header";
import AllProviders from "@/providers";


export const metadata: Metadata = {
  title: "Music App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="dark:bg-amber-700"
      >
        {/* <NextThemeProvider> */}
        <AllProviders>
          <Header/>
          {children}
        </AllProviders>
          {/* </NextThemeProvider> */}
        
      </body>
    </html>
  );
}
